### ISSUE TITLE
AttributeError: module 'uvloop' has no attribute 'EventLoopPolicy'

### ISSUE THREAD

**Issue by Spritan** [AnswerDotAI/fasthtml#144]
```python
from fasthtml.common import *

app,rt = fast_app()

@rt('/')
def get(): return Div(P('Hello World!'), hx_get="/change")

serve()
```

Error I faced

```shell
(.conda) (base) ➜  htmxtesting python index.py 
Link: http://localhost:5001
INFO:     Will watch for changes in these directories: ['/run/media/spritan/sda3/Github/htmxtesting']
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     Started reloader process [115441] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/run/media/spritan/sda3/Github/htmxtesting/.conda/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/run/media/spritan/sda3/Github/htmxtesting/.conda/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/spritan/.local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/home/spritan/.local/lib/python3.11/site-packages/uvicorn/server.py", line 64, in run
    self.config.setup_event_loop()
  File "/home/spritan/.local/lib/python3.11/site-packages/uvicorn/config.py", line 477, in setup_event_loop
    loop_setup(use_subprocess=self.use_subprocess)
  File "/home/spritan/.local/lib/python3.11/site-packages/uvicorn/loops/auto.py", line 11, in auto_loop_setup
    uvloop_setup(use_subprocess=use_subprocess)
  File "/home/spritan/.local/lib/python3.11/site-packages/uvicorn/loops/uvloop.py", line 7, in uvloop_setup
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
                                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'uvloop' has no attribute 'EventLoopPolicy'
```

**Comment by GirishKumarSharma** [comment]
I didn't got any error when I run the code in fasthtml unziped folder i.e. : 
(env) girish@mypc:~/Downloads/fasthtml-main$ pwd
/home/girish/Downloads/fasthtml-main
(env) girish@mypc:~/Downloads/fasthtml-main$ python bb.py

**Comment by jph00** [comment]
Please don't use gh issues for support - use Discord for that.
