### ISSUE TITLE
`fh_railway_deploy` error: unexpected argument '-c' found

### ISSUE THREAD

**Issue by swyxio** [AnswerDotAI/fasthtml#186]
running thru the basic tutorial deploy and immediately ran into this

```bash
 fh_railway_deploy ainews_dev 
# railway init -n ainews_dev
Created project ainews_dev on Personal
https://railway.app/project/cc54b68d-ae97-4b10-8ff6-83fe888600ad
# railway up -c
error: unexpected argument '-c' found

  tip: to pass '-c' as a value, use '-- -c'

Usage: railway up [OPTIONS] [PATH]

For more information, try '--help'.
# railway domain
Project does not have any services
error: unexpected argument '-e' found

  tip: to pass '-e' as a value, use '-- -e'

Usage: railway link [OPTIONS] [PROJECT_ID] [SERVICE]

For more information, try '--help'.
Traceback (most recent call last):
  File "/Users/swyx/Documents/Work/ainews/env/bin/fh_railway_deploy", line 8, in <module>
    sys.exit(railway_deploy())
             ^^^^^^^^^^^^^^^^
  File "/Users/swyx/Documents/Work/ainews/env/lib/python3.12/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swyx/Documents/Work/ainews/env/lib/python3.12/site-packages/fasthtml/cli.py", line 45, in railway_deploy
    railway_link.__wrapped__()
  File "/Users/swyx/Documents/Work/ainews/env/lib/python3.12/site-packages/fasthtml/cli.py", line 24, in railway_link
    res = check_output(cmd.split())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swyx/miniconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swyx/miniconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['railway', 'link', '-e', '14fddd01-f52f-4ddf-bbe3-ad361d1ebee8', '-p', 'cc54b68d-ae97-4b10-8ff6-83fe888600ad', '-s', 'None']' returned non-zero exit status 2.
```

my workaround

```bash
railway up
railway domain
railway link
railway volume add -m /app/data # error: unrecognized subcommand 'volume' 
```

**Comment by swyxio** [comment]
also  this error

```bash
railway volume add -m /app/data
error: unrecognized subcommand 'volume'

Usage: railway [OPTIONS] <COMMAND>

For more information, try '--help'.

```

**Comment by jph00** [comment]
You need a more recent version of the CLI.
