### ISSUE TITLE
Websocket example is giving html is not defined error

### ISSUE THREAD

**Issue by manojlds** [AnswerDotAI/fasthtml#281]
I am on fasthtml 0.3.4

I was trying out the basic_ws.py example:

```python
from asyncio import sleep
from fasthtml.common import *

app = FastHTML(ws_hdr=True)
rt = app.route

def mk_inp(): return Input(id='msg')
nid = 'notifications'

@rt('/')
async def get():
    cts = Div(
        Div(id=nid),
        Form(mk_inp(), id='form', ws_send=True),
        hx_ext='ws', ws_connect='/ws')
    return Titled('Websocket Test', cts)

async def on_connect(send): await send(Div('Hello, you have connected', id=nid))
async def on_disconnect( ): print('Disconnected!')

@app.ws('/ws', conn=on_connect, disconn=on_disconnect)
async def ws(msg:str, send):
    await send(Div('Hello ' + msg, id=nid))
    await sleep(2)
    return Div('Goodbye ' + msg, id=nid), mk_inp()

serve()
```

Running it gives the following error in the browser:

```
Uncaught ReferenceError: htmx is not defined
    at ws.js:11:3
    at ws.js:467:3
```

Same error when trying the chat bot with ws exxample.

**Comment by manojlds** [comment]
Should the extension be loaded after htmx is? This is what I see now:

```html
<script src="https://unpkg.com/htmx-ext-ws/ws.js"></script>
<script src="https://unpkg.com/htmx.org@next/dist/htmx.min.js"></script>
```

**Comment by jph00** [comment]
Yeah I fixed that yesterday - update your pip install.
