### ISSUE TITLE
Variable type routing error should throw 404 errors

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#37]
Assuming this view:

```python
from fasthtml.fastapp import * 

app = fast_app()

@app.get("/{name}/{age}")
def namer(name: str, age: int):
  return Titled(f"Hello {name.title()}, age {age}")

run_uv()
```

If I go to this URL: http://127.0.0.1:5001/uma/five, bcause the second named variable is a `str` instead of an `int`, it throws an error.

```python
INFO:     127.0.0.1:52909 - "GET /Uma/asdsad HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/fasthtml/core.py", line 227, in _f
    wreq = await _wrap_req(req, params)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/fasthtml/core.py", line 167, in _wrap_req
    return [await _find_p(req, arg, p) for arg,p in params.items()]
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/fasthtml/core.py", line 167, in <listcomp>
    return [await _find_p(req, arg, p) for arg,p in params.items()]
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/fasthtml/core.py", line 164, in _find_p
    return [anno(o) for o in res] if isinstance(res,list) else anno(res)
  File "/Users/daniel.roy.greenfeld/.virtualenvs/super-dashboard/lib/python3.10/site-packages/fasthtml/core.py", line 77, in str2int
    return 0 if not s else int(s)
ValueError: invalid literal for int() with base 10: 'asdsad'
```

If I'm not mistaken, this should be a 404 error, right?

**Comment by jph00** [comment]
Yes it would be great to make that a 404!

**Comment by jph00** [comment]
Done :D
